apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: buzzard-python 
  janus-idp.io/tekton: buzzard-python
  backstage.io/kubernetes-id: buzzard-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: buzzard-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  