apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: buzzard-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:2eb314280199ca46bf2a8531ea4876c26b6d7bda@sha256:c2c644eaeffbcb6a2aab93cfc3f48fd4977759b89274c65972c1058bb9cad687
          name: container-image
